import type { TranscriptChunkResult } from "../shared/transcript";
import { chunkTranscriptSegments, type TranscriptSegment } from "./transcript-reader";
import { cachedSegments, toTranscriptSegments, type HttpSegment } from "./transcript-segments";

const INNERTUBE_BASE = "https://www.youtube.com/youtubei/v1";
const WEB_CLIENT_VERSION = "2.20260206.01.00";
const ANDROID_CLIENT_VERSION = "20.10.38";
const ANDROID_USER_AGENT = `com.google.android.youtube/${ANDROID_CLIENT_VERSION} (Linux; U; Android 14)`;
const VIDEO_SEARCH_PARAMS = "EgIQAQ%3D%3D";
const SEARCH_TIMEOUT_MS = 10_000;
const TRACK_TIMEOUT_MS = 10_000;

interface VideoSummary {
  videoId: string;
  url: string;
  title: string;
  channelName?: string;
}

interface CaptionTrack {
  languageCode: string;
  name: string;
  isAutoGenerated: boolean;
  baseUrl: string;
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null;
}

function getRecord(value: unknown): Record<string, unknown> | null {
  return isRecord(value) && !Array.isArray(value) ? value : null;
}

function collectObjects(
  value: unknown,
  key: string,
  found: Record<string, unknown>[] = [],
): Record<string, unknown>[] {
  if (Array.isArray(value)) {
    for (const item of value) collectObjects(item, key, found);
    return found;
  }
  const record = getRecord(value);
  if (record === null) return found;
  if (key in record) found.push(record);
  for (const item of Object.values(record)) collectObjects(item, key, found);
  return found;
}

function textFromRuns(value: unknown): string | undefined {
  const record = getRecord(value);
  const simple = record?.simpleText;
  if (typeof simple === "string" && simple.length > 0) return simple;
  const runs = record?.runs;
  if (!Array.isArray(runs)) return undefined;
  const text = runs
    .map((run) => (getRecord(run)?.text as string | undefined) ?? "")
    .join("")
    .trim();
  return text.length > 0 ? text : undefined;
}

function videoIdFromLocation(location: Location): string | null {
  try {
    const url = new URL(location.href);
    const queryId = url.searchParams.get("v");
    if (queryId !== null && /^[\w-]{11}$/.test(queryId)) return queryId;
    const pathParts = url.pathname.split("/").filter(Boolean);
    for (const marker of ["shorts", "live", "embed", "v"]) {
      const index = pathParts.indexOf(marker);
      const candidate = index >= 0 ? pathParts[index + 1] : undefined;
      if (candidate !== undefined && /^[\w-]{11}$/.test(candidate)) return candidate;
    }
    return null;
  } catch {
    return null;
  }
}

async function innertubePost(
  endpoint: string,
  body: Record<string, unknown>,
  headers: Record<string, string>,
): Promise<unknown> {
  const response = await fetch(`${INNERTUBE_BASE}/${endpoint}?prettyPrint=false`, {
    method: "POST",
    headers: { "content-type": "application/json", ...headers },
    body: JSON.stringify(body),
    signal: AbortSignal.timeout(SEARCH_TIMEOUT_MS),
  });
  if (!response.ok) {
    throw new Error(`YouTube ${endpoint} request failed with ${String(response.status)}.`);
  }
  return response.json();
}

function webContext(): Record<string, unknown> {
  const language = navigator.language || "en";
  return { client: { clientName: "WEB", clientVersion: WEB_CLIENT_VERSION, hl: language } };
}

function parseSearchResult(renderer: Record<string, unknown>): VideoSummary | null {
  const videoId = typeof renderer.videoId === "string" ? renderer.videoId : undefined;
  const title = textFromRuns(renderer.title);
  if (videoId === undefined || title === undefined) return null;
  const channelName = textFromRuns(renderer.ownerText ?? renderer.longBylineText);
  return {
    videoId,
    url: `https://www.youtube.com/watch?v=${videoId}`,
    title,
    ...(channelName === undefined ? {} : { channelName }),
  };
}

export async function searchVideos(query: string, limit: number): Promise<VideoSummary[]> {
  const response = await innertubePost(
    "search",
    { context: webContext(), query, params: VIDEO_SEARCH_PARAMS },
    { "x-youtube-client-name": "1", "x-youtube-client-version": WEB_CLIENT_VERSION },
  );
  const renderers = collectObjects(response, "videoRenderer");
  const results: VideoSummary[] = [];
  for (const wrapper of renderers) {
    const parsed = parseSearchResult(wrapper.videoRenderer as Record<string, unknown>);
    if (parsed !== null) results.push(parsed);
    if (results.length >= limit) break;
  }
  return results;
}

function decodeEntities(value: string): string {
  return value
    .replace(/&amp;/g, "&")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .replace(/&apos;/g, "'");
}

function parseTranscriptXml(xml: string): HttpSegment[] {
  const segments: HttpSegment[] = [];
  const paragraphPattern = /<p\s+t="(\d+)"\s+d="(\d+)"[^>]*>([\s\S]*?)<\/p>/g;
  let match: RegExpExecArray | null;
  while ((match = paragraphPattern.exec(xml)) !== null) {
    const offset = Number.parseInt(match[1] ?? "0", 10) / 1_000;
    const duration = Number.parseInt(match[2] ?? "0", 10) / 1_000;
    const text = decodeEntities(
      (match[3] ?? "")
        .replace(/<[^>]+>/g, "")
        .replace(/\n/g, " ")
        .trim(),
    );
    if (text.length > 0) segments.push({ offsetSeconds: offset, durationSeconds: duration, text });
  }
  if (segments.length > 0) return segments;
  const legacyPattern = /<text start="([^"]*)" dur="([^"]*)">([^<]*)<\/text>/g;
  while ((match = legacyPattern.exec(xml)) !== null) {
    const text = decodeEntities((match[3] ?? "").replace(/<[^>]+>/g, "").trim());
    if (text.length > 0) {
      segments.push({
        offsetSeconds: Number.parseFloat(match[1] ?? "0"),
        durationSeconds: Number.parseFloat(match[2] ?? "0"),
        text,
      });
    }
  }
  return segments;
}

function trackName(track: Record<string, unknown>): string {
  return textFromRuns(track.name) ?? "";
}

function pickCaptionTrack(tracks: CaptionTrack[]): CaptionTrack | null {
  if (tracks.length === 0) return null;
  const language = (navigator.language || "en").split("-")[0] ?? "en";
  const preferred = tracks.filter((track) => track.languageCode.startsWith(language));
  const candidates = preferred.length > 0 ? preferred : tracks;
  return candidates.find((track) => !track.isAutoGenerated) ?? candidates[0] ?? null;
}

async function fetchCaptionTracks(videoId: string): Promise<CaptionTrack[]> {
  const response = await innertubePost(
    "player",
    {
      context: { client: { clientName: "ANDROID", clientVersion: ANDROID_CLIENT_VERSION } },
      videoId,
    },
    { "User-Agent": ANDROID_USER_AGENT },
  );
  const tracks = collectObjects(response, "captionTracks").flatMap((wrapper) =>
    Array.isArray(wrapper.captionTracks) ? wrapper.captionTracks : [],
  );
  const parsed: CaptionTrack[] = [];
  for (const entry of tracks) {
    const record = getRecord(entry);
    if (record === null) continue;
    const baseUrl = record.baseUrl;
    const languageCode = record.languageCode;
    if (typeof baseUrl !== "string" || typeof languageCode !== "string") continue;
    let hostname = "";
    try {
      hostname = new URL(baseUrl).hostname;
    } catch {
      continue;
    }
    if (!hostname.endsWith(".youtube.com")) continue;
    parsed.push({
      languageCode,
      name: trackName(record),
      isAutoGenerated: record.kind === "asr",
      baseUrl,
    });
  }
  return parsed;
}

async function loadHttpSegments(videoId: string): Promise<TranscriptSegment[]> {
  return cachedSegments(`youtube:${videoId}`, async () => {
    const tracks = await fetchCaptionTracks(videoId);
    const track = pickCaptionTrack(tracks);
    if (track === null) throw new Error("No caption tracks are available for this video.");
    const response = await fetch(track.baseUrl, {
      signal: AbortSignal.timeout(TRACK_TIMEOUT_MS),
    });
    if (!response.ok) throw new Error("The caption track could not be fetched.");
    const segments = toTranscriptSegments(parseTranscriptXml(await response.text()));
    if (segments.length === 0) throw new Error("The caption track is empty.");
    return segments;
  });
}

export async function readHttpTranscriptChunk(
  location: Location,
  cursor: number,
  maxChars: number,
  afterSegmentKey: string,
): Promise<TranscriptChunkResult> {
  const videoId = videoIdFromLocation(location);
  if (videoId === null) {
    return { available: false, reason: "No YouTube video is open on this page." };
  }
  try {
    const segments = await loadHttpSegments(videoId);
    return chunkTranscriptSegments(segments, cursor, maxChars, afterSegmentKey);
  } catch (error: unknown) {
    return {
      available: false,
      reason:
        error instanceof Error
          ? `The direct transcript path failed: ${error.message}`
          : "The direct transcript path failed.",
    };
  }
}

export async function handleYouTubeSearch(payload: {
  query: string;
  limit: number;
}): Promise<{ message: string; data: unknown }> {
  try {
    const results = await searchVideos(payload.query, payload.limit);
    if (results.length === 0) {
      return { message: "No videos matched the search.", data: { results: [] } };
    }
    return { message: `Found ${String(results.length)} videos.`, data: { results } };
  } catch (error: unknown) {
    const detail =
      error instanceof Error && error.name === "TimeoutError"
        ? "The YouTube search request timed out."
        : error instanceof Error
          ? error.message
          : "The YouTube search request failed.";
    throw new Error(
      `${detail} Direct YouTube search only works while this tab is on youtube.com; navigate to https://www.youtube.com and retry.`,
    );
  }
}
